name: "Release"

on:
  push:
    tags:
    - 'v*.*.*'

env:
  EXT_NAME: extension.vsix

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Set tag env
        run: echo "GIT_TAG=`echo ${GITHUB_REF_NAME} | cut -c 2-6`" >> $GITHUB_ENV

      - name: Set file name
        run: echo "EXT_NAME=gitstash-${GIT_TAG}.vsix" >> $GITHUB_ENV

      - name: Info
        run: echo "============================ $EXT_NAME ============================"

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install dependencies
        run: npm install

      - name: Create archive
        run: npx vsce package

      - name: GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          artifacts: ${{ env.EXT_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifactContentType: application/zip
          artifactErrorsFailBuild: true

      - name: Marketplace Release
        run: npx vsce publish --packagePath ${{ env.EXT_NAME }}
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
