name: "Release tagged version"

on:
  push:
    tags:
    - 'v*.*.*'

env:
  # These variables are redefined
  GIT_TAG: 0.0.0
  EXT_NAME: gitstash.vsix

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Get the tag without prefix
        run: echo "GIT_TAG=`echo ${GITHUB_REF_NAME} | cut -c2-`" >> $GITHUB_ENV

      - name: Set the extension filename
        run: echo "EXT_NAME=gitstash-${GIT_TAG}.vsix" >> $GITHUB_ENV

      - name: File to process
        run: echo "*** $EXT_NAME ***"

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install dependencies
        run: npm install

      - name: Create archive
        run: npx vsce package

      - name: Generate release notes
        id: release-notes
        uses: RedCrafter07/release-notes-action@v1.0.1
        with:
          tag-name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: ðŸš€ ${{ env.GIT_TAG }}
          body: ${{ env.RELEASE_NOTES }}
          artifacts: ${{ env.EXT_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifactContentType: application/zip
          artifactErrorsFailBuild: true
        env:
          RELEASE_NOTES: ${{ steps.release-notes.outputs.release-notes }}

      - name: Marketplace Release
        run: npx vsce publish --packagePath ${{ env.EXT_NAME }}
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
